future: true
url: "https://newhigen.github.io"
baseurl: "/books"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

google_analytics: G-8H5FW1Q707

plugins:
  - jekyll-sitemap
